### ISSUE TITLE
First request returns 401

### ISSUE THREAD

**Issue by biemster** [biemster/FindMy#1]
When running `request_reports.sh` the first time, it returns an authorization error. Subsequent requests run fine (so the workaround is to just run it again).

**Comment by biemster** [comment]
This might have been resolved when the RINFO routing info got hardcoded to 17106176 in commit ae726a7, because I haven't seen this behavior for a while. Close in a couple of days if it does not come back.

**Comment by olivluca** [comment]
FWIW I get the 401 if I leave the virtual machine unattended for a while or save and restore it (I'm using virtualbox).
Just one repeat isn't enough, I have to try several times before the 401 error disappears, at times I have to log out and log in again.
Also, from time to time it prompts me for my password, even if I clicked the button "always allow", which makes wrapping the script behind a tcp socket almost impossible (but then maybe it's because I'm not familiar with macos and I don't know which setting I have to touch to avoid it).

**Comment by biemster** [comment]
Yeah this is also my only use for macos, and I'm also randomly getting the password prompt. I'm working on a minimal macos with only the iCloud login and FindMy token retrieval, but it might take a while before I have something usable.
